const symbols=['AAPL','MSFT','NVDA','SPY','QQQ'];let active='AAPL';
const money=n=>n?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n):'—';
const compact=n=>new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(n);
async function json(url){const r=await fetch(url);const p=await r.json();if(!r.ok)throw new Error(p.error||`HTTP ${r.status}`);return p}
function tick(){document.querySelector('#clock').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})}setInterval(tick,1000);tick();
async function status(){try{const s=await json('/api/market/status');document.querySelector('#feed-name').textContent=`${s.provider.toUpperCase()} · ${s.feed.toUpperCase()}`;document.querySelector('#coverage').textContent=s.coverage;document.querySelector('#notice').textContent=s.notice;document.querySelector('#mode').textContent=s.synthetic?'SYNTHETIC DEMO · READ ONLY':'LIVE DATA · READ ONLY';document.querySelector('#feed-dot').classList.add('live')}catch(e){document.querySelector('#feed-name').textContent='OFFLINE'}}
async function quotes(){const root=document.querySelector('#quote-grid');try{const d=await json(`/api/quotes?symbols=${symbols.join(',')}`);root.innerHTML=d.quotes.map(q=>`<div class="quote" data-symbol="${q.symbol}"><div><strong>${q.symbol}</strong><br><small>Vol ${compact(q.volume)}</small></div><div class="change"><span class="price">${money(q.price)}</span><br><small class="${q.change>=0?'up':'down'}">${q.change>=0?'+':''}${q.change.toFixed(2)} · ${q.change_percent.toFixed(2)}%</small></div></div>`).join('');root.querySelectorAll('.quote').forEach(el=>el.onclick=()=>{active=el.dataset.symbol;document.querySelector('#symbol-select').value=active;history()});document.querySelector('#updated').textContent=`UPDATED ${new Date().toLocaleTimeString()}${d.cached?' · CACHED':''}`}catch(e){root.innerHTML=`<div class="loading">${e.message}</div>`}}
function draw(bars){const svg=document.querySelector('#chart'),w=760,h=310,p=35;svg.innerHTML=`<defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#0b8a56" stop-opacity=".20"/><stop offset="1" stop-color="#0b8a56" stop-opacity="0"/></linearGradient></defs>`;if(!bars.length){document.querySelector('#chart-empty').classList.remove('hidden');return}document.querySelector('#chart-empty').classList.add('hidden');const vals=bars.map(b=>b.close),min=Math.min(...vals),max=Math.max(...vals),span=max-min||1;for(let i=0;i<5;i++){const y=p+(h-2*p)*i/4,val=max-span*i/4;svg.insertAdjacentHTML('beforeend',`<line class="grid-line" x1="${p}" y1="${y}" x2="${w-p}" y2="${y}"/><text class="chart-label" x="${w-p}" y="${y-6}" text-anchor="end">${val.toFixed(2)}</text>`)}const pts=vals.map((v,i)=>`${p+(w-2*p)*i/(vals.length-1||1)},${p+(max-v)*(h-2*p)/span}`);svg.insertAdjacentHTML('beforeend',`<path class="chart-area" d="M${pts[0]} L${pts.join(' L')} L${w-p},${h-p} L${p},${h-p} Z"/><path class="chart-line" d="M${pts.join(' L')}"/>`);document.querySelector('#range').textContent=`${money(min)} — ${money(max)}`}
async function history(){document.querySelector('#chart-title').textContent=`${active} · 90 days`;try{const d=await json(`/api/history/${active}?days=90&timeframe=1Day&limit=90`);draw(d.bars)}catch(e){document.querySelector('#chart-empty').textContent=e.message;document.querySelector('#chart-empty').classList.remove('hidden')}}
const select=document.querySelector('#symbol-select');select.innerHTML=symbols.map(s=>`<option>${s}</option>`).join('');select.onchange=e=>{active=e.target.value;history()};document.querySelector('#refresh').onclick=quotes;status();quotes();history();setInterval(quotes,15000);
